apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  volumeName: local-pv
  resources:
    requests:
      storage: 500Mi