apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-log-1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  volumeName: pv-log
  resources:
    requests:
      storage: 50Mi
